steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'functions'
  - 'deploy'
  - '--gen2'
  - '--project=axon-a4b3b'
  - '--region=europe-west1'
  - '--runtime=python311'
  - '--source=.'
  - '--entry-point=process_sparc'
  - '--trigger-event-filters=type=google.cloud.firestore.document.v1.updated'
  - '--trigger-event-filters=database=(default)'
  - '--trigger-event-filters-path-pattern=document=users/{uid}/sessions/{sessionId}'
  - '--set-env-vars=BUCKET_NAME=axon-bucket'
  - '--memory=512MB'
  - '--timeout=540s'
  - 'process-sparc'
